# Generated by Django 2.2.1 on 2019-05-22 20:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EsnAuthToken',
            fields=[
                ('nanoid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('expire_at', models.DateTimeField(default=datetime.datetime(2019, 5, 23, 20, 56, 15, 699750))),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('url', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('maintenance', models.BooleanField()),
                ('logo_url', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('url', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('page_data', models.TextField(default='')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pages', to='api.SiteSettings')),
            ],
        ),
    ]
